server:
  port: 10001

spring:
  profiles:
    active: ${ACTIVE:dev}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/edu-sys?useUnicode=true&characterEncoding=utf-8&useSSL=fals
    username: root
    password: 123456